### ISSUE TITLE
conflict with Repurposed Structures

### ISSUE THREAD

**Issue by MoonMoonShark** [mystiacraft/instantlava#5]
**Your Environment**
- InstantLava version: InstantLava_Forge1.16.1-1.2.1.jar
- Minecraft version: 1.16.5
- Mod loader (Forge or Fabric): Forge
- Mod loader version: forge-36.0.43

**Describe the bug**

conflict with Repurposed Structures. i can run the game with one or the other, but not both together. 
https://www.curseforge.com/minecraft/mc-mods/repurposed-structures

**Steps to reproduce:**
1. create new Curseforge profile
2. add both InstantLava and Repurposed Structures mods
3. hit Play

**Does this issue occur when you only use this mod?:**
 No

[latest.log](https://github.com/mystiacraft/instantlava/files/6080887/latest.log)
[crash-2021-03-03_23.38.12-fml.txt](https://github.com/mystiacraft/instantlava/files/6080910/crash-2021-03-03_23.38.12-fml.txt)

_Thank you for reporting the bug!_

**Comment by parly** [comment]
Thanks for reporting. Fixed in [v1.2.2](https://www.curseforge.com/minecraft/mc-mods/instantlava/files/3226165).

**Comment by MoonMoonShark** [comment]
thank you!!!
